config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'


  get '/config/new', to: 'config#new', as: 'new_config'
  post '/config/reload', to: 'config#reload', as: 'reload_config'
  get '/config/restore', to: 'config#restore', as: 'restore_config'
  get '/config/:uid/:version/edit', to: 'config#edit', as: 'edit_config_version'
  get '/config/:uid/edit', to: 'config#edit', as: 'edit_config'

  get '/config/:uid/:version', to: 'config#show', as: 'config_version'
  get '/config/:uid', to: 'config#show', as: 'config'

  resources :config, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/config_controller.rb
class ConfigController < ApplicationController
  include ConfigHelper

  def new
    @config = OrbitalConfig.new
    if params[:config] && valid_json?(params[:config][:json])
      @config.deserialize_from_json(params[:config][:json])
    end
  end

  def reload
    @config = OrbitalConfig.new
    if params[:config] && valid_json?(params[:config][:json])
      @config.deserialize_from_json(params[:config][:json])
    end
  end

  def edit
    @config = load_config
  end

  def create
    @config = OrbitalConfig.new(params.require(:orbital_config).permit!)

    if @config.save
      redirect_to config_pretty_display_url(@config), notice: 'Config generated successfully:'
    else
      render 'new'
    end
  end

  def restore
  end

  def show
    @config = load_config
  end

  private

  def valid_json?(json)
    !!JSON.parse(json)
  rescue JSON::ParserError => _e
    false
  end

  def load_config
    @config = OrbitalConfig.find_by!(uid: params[:uid], version: (params[:version] || 0))
    @config.deserialize_from_json(@config.data)
    @config
  end
end

app/helpers/config_helper.rb
module ConfigHelper
  def display_value_for(attr)
    OrbitalConfig.type_for_attribute(attr.to_s).deserialize(@config.send(attr))
  end

  def config_pretty_display_url(config)
    if !config.version || config.version == 0
      config_url(config.uid)
    else
      config_version_url(config.uid, config.version)
    end
  end
end

app/views/config/_form.html.slim
= simple_form_for @config, url: config_index_path, method: :post do |f|
  = f.input :location_id, label: 'Location ID', as: :integer, required: true,
          placeholder: "Can be any unique positive integer, as long as it's unique among all the locations", hint: 'check existing location ids in https://wiki.grab.com/display/GEO/Orbital+Queue+Config'
  = f.input :location_name, required: true, placeholder: 'e.g. KLIA', hint: 'Your custom location name, this will be used in message sent to dax, so be sure to use native language here'
  = f.input :location_url, placeholder: 'e.g. http://bit.ly/dmkqueue', hint: 'You can put a URL here and reference it in your message content'
  = f.input :message_config_id, required: true, placeholder: 'e.g. malay', hint: 'Check https://wiki.grab.com/display/GEO/Orbital+Queue+Config for message config id.'
  = f.input :vehicle_type_names, label: 'Vehicle type and names', required: true,
          input_html: { value: display_value_for(:vehicle_type_names) },
          placeholder: 'e.g. "302": "JustGrab - Airport", "400": "Taxi - Airport"',
          hint: 'Comma separated pairs with taxi type ID and taxi type name. The name will be used in the notifications.'
  = f.input :vehicle_type_min_balances, label: 'Vehicle type and minimal balance required',
          input_html: { value: display_value_for(:vehicle_type_min_balances) },
          placeholder: 'e.g. "302": 1000, "400": 2000',
          hint: 'Comma separated pairs with taxi type ID and taxi type minimal balance required. Drivers does not have minimal balance will not be able to enqueue'
  = f.input :pickup_area_geo, required: true,
          input_html: { value: display_value_for(:pickup_area_geo) },
          hint: 'Comma separated geohash strings, max geohash level 12, you can also combine different levels of geohash',
          placeholder: 'e.g. w22r96, w22r97'
  = f.input :bay_area_geo, required: true,
          input_html: {value: display_value_for(:bay_area_geo) },
          hint: 'Comma separated geohash strings, max geohash level 12, you can also combine different levels of geohash',
          placeholder: 'e.g. w22r61, w22r63'
  = f.input :whitelist_enabled, placeholder: 'false', hint: 'If you set this field to true, you must set orbitalDaxWhitelist variable in ExP'

  .badge.badge-light Notification Frequency
  br
  br

  = f.input :queue_position_multiple,
          placeholder: 'Leave blank to use the default value: 5',
          hint: 'We will send a notification to driver after he has moved X positions in the queue. You may consider increasing this value for large queues.'

  = f.input :queue_position_dynamic_multiple,
          input_html: { value: display_value_for(:queue_position_dynamic_multiple) },
          placeholder: "e.g. \"200\": 50, \"500\": 100\n(Leave blank to disable the feature, recommend to set this for very large queues).",
          hint: "(Optional) Comma separated pairs with the value of queue position and the key of the length of the range.\
          This defines the frequency of the notifications based on current queue position of drivers. e.g. \"500\": 100 means when the\
          queue position of driver is greater than 500, we will send a update message to the driver when his queue position number has change\
          by 100."

  = f.input :ignore_quota,
          placeholder: 'Leave blank to use the default value: 2',
          hint: 'Number of ignores by driver to move driver back to the end of queue position, if you make it 1, it means dax is not able to ignore at all. So for example, if you want dax be able to ignore 2 times, you need to set ignore quota 3.'
  = f.input :cancel_quota,
          placeholder: 'Leave blank to use the default value: 0',
          hint: 'Number of cancels by driver to move driver back to the end of queue position, if you make it 1, it means dax is not able to cancel at all. So for example, if you want dax be able to cancel 2 times, you need to set cancel quota 3.'
  = f.input :mercy_period_in_sec,
          placeholder: 'Leave blank to use the default value: 300',
          hint: 'Number of seconds after the driver turn off app or moved out of the bay area to be moved to the end of queue position'
  = f.input :remind_snooze_time_in_sec,
          placeholder: 'Leave blank to use the default value: 60',
          hint: 'If value is 180, when driver turn off app or moved out of bay area, driver will get the "Out Of Queue Remind Message" every 3 mins after receiving the first "Out of Queue Remind Message"'
  = f.input :remind_before_in_sec,
          placeholder: 'Leave blank to use the default value: 180',
          hint: 'The time we send the 1st "Out of Queue Remind Message". If value is 300, we will send this 5 mins before "mercy period in sec" ends.'

  .badge.badge-light Short-Distance Job settings
  br
  br
  .text In order to let the last job to be considered as short distance job for a dax when dax goes into queue, that job should meet some requirements:
  .text 1) Job must be accepted & completed, and dax must go back to queue in Z seconds, defined by "short distance job record ttl in sec" field.
  .text 2) Job has a trip distance (pickup->dropoff) which less than threshold distance kms which defined by "short distance job distance".
  br
  br
  = f.input :short_distance_job_record_ttl_in_sec, placeholder: '0', hint: 'dax must return queue after he accepted last short job in this time value'
  = f.input :short_distance_job_distance, placeholder: '0 meter', hint: 'if last job in queue has a short distance(less than this value unit is meter), dax will be directly put to the priority queue'

  .badge.badge-light B2BJ settings
  br
  br
  .text When driver first enters the queue waiting area, the following additional check should be done -
  .text Is the driver's last completed job (a) was completed within the last Z (= 60 default) mins, and (b) had dropoff within area Y, and (c) had trip length of > X ms
  .text If not, put them in the other queues (main queue or short distance job queue) as normal.
  .text If so, put them in this b2bj queue.
  br
  br
  = f.input :b2bj_area_geo, required: false,
          input_html: {value: display_value_for(:b2bj_area_geo) },
          hint: 'Comma separated geohash strings, max geohash level 12, you can also combine different levels of geohash, Note that this cannot be overlapped with bay area geohash',
          placeholder: 'e.g. w22r61, w22r63'
  = f.input :b2bj_record_ttl_in_sec, placeholder: '0', hint: 'last completed job was completed within the last Z (= 60 default) mins'
  = f.input :b2bj_distance, placeholder: '0 meter', hint: 'last completed job had trip length of > X ms'
  = f.hidden_field :uid

  = f.button :submit, 'Generate', class: 'btn-success'

app/views/config/edit.html.slim
h2 Orbital Config Generator

= render 'form'

app/views/config/new.html.slim
h2 Orbital Config Generator

div
  span Already have a generated JSON config?&nbsp
  span = link_to 'Load and modify existing config', restore_config_path()
br

= render 'form'

app/views/config/reload.html.slim
h2 Orbital Config Generator

div
  span Already have a generated JSON config?&nbsp
  span = link_to 'Load and modify existing config', restore_config_path()
br

= render 'form'

app/views/config/restore.html.slim
- json = @config ? @config.serialize_to_json : ""


= simple_form_for :config, url: reload_config_path, method: :post do |f|
  = f.input :json, label: false, required: false, as: :text,
          placeholder: 'Paste the generated JSON here',
          input_html: {value: json, rows: json.present? ? json.lines.count : 15}
  = f.button :submit, "Modify Again", class: "btn-info"

app/views/config/show.html.slim
- json = @config.serialize_to_json
- url = config_pretty_display_url(@config)
div
  span You may share this config using the link:&nbsp
  span= link_to url, url

br

style = Diffy::CSS


- prev_config = @config.version > 0 ? OrbitalConfig.find_by(uid: @config.uid, version: @config.version - 1) : nil


div.btn-group role="group"
  = link_to "Modify again", edit_config_version_path(@config.uid, @config.version), class: 'btn btn-sm btn-secondary'
  button.clipboard-btn.btn.btn-sm.btn-info data-clipboard-action="copy" data-clipboard-target="#jsonResult"
    | Copy the generated JSON to clipboard
.clearfix
br

p Changes made in this version:
div = Diffy::Diff.new(prev_config&.pretty_print_data || '', @config.pretty_print_data).to_s(:html_simple).html_safe

textarea#jsonResult rows="0" style="height: 0; width: 0;"
  = json