config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'


  get '/config/new', to: 'config#new', as: 'new_config'
  post '/config/reload', to: 'config#reload', as: 'reload_config'
  get '/config/restore', to: 'config#restore', as: 'restore_config'
  get '/config/:uid/:version/edit', to: 'config#edit', as: 'edit_config_version'
  get '/config/:uid/edit', to: 'config#edit', as: 'edit_config'

  get '/config/:uid/:version', to: 'config#show', as: 'config_version'
  get '/config/:uid', to: 'config#show', as: 'config'

  resources :config, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to "Orbital", root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        = link_to "Generate Config", new_config_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Orbital
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .container
      header
        = render 'layouts/navigation'
      main role="main"
        = render 'layouts/messages'
        = yield